### ISSUE TITLE
Feature request: enhance ExtendedFields/Tags to support name mapping

### ISSUE THREAD

**Issue by tom-englert** [pada57/serilog-sinks-influxdb#20]
**Current**: Extended fields and tags (#16) use the property name as a tag or field name.
**Request**: Both property and field/tag name can be specified.
**Suggestion**: Allow to specify both log property name and field/tag name delimited by `:` (minimal changes and fully backward compatible). 
```json
"sinkOptions": {
  "ExtendedTags": [ "SourceContext:component_name", "Application:app_name" ],
```

**Comment by pada57** [comment]
@tom-englert  is those extended targ/field value "component_name" can be variables to be resolved or just raw text ? "appname" to be replaced at runtime ?

**Comment by tom-englert** [comment]
These are just two names, the first is the serilog property's name, and the second the influx tag or field name.
