### ISSUE TITLE
ApplicationName/InstanceName should be optional

### ISSUE THREAD

**Issue by tom-englert** [pada57/serilog-sinks-influxdb#23]
To give more flexibility, `ApplicationName `and `InstanceName` should be optional.

E.g. in our company we need to use `app_name` instead of `appname`, so with optional `ApplicationName` the config would look like this:
```json
"WriteTo": {
  "InfluxDB": {
    "Name": "InfluxDB",
    "Args": {
      "sinkOptions": {
        "ExtendedTags": [ "SourceContext:component_name", "Application:app_name", "Facility:facility" ],
        "ExtendedFields": [ "FacilityCode:facility_code" ],
        "ConnectionInfo": { ... }
      }
    }
  }
},
"Properties": {
  "Application": "MyApplicationName",
  "Facility": "user",
  "FacilityCode": 1
}

```

**Comment by pada57** [comment]
@tom-englert  by actively depends what you mean. i will try to do best on personal time. Also not using currently anymore influxdb at work that's why low priority

**Comment by tom-englert** [comment]
That's fine, just wanted to make sure this is not a dead end.
