### ISSUE TITLE
Bug: Process id should be a string in V1

### ISSUE THREAD

**Issue by MarkZither** [pada57/serilog-sinks-influxdb#29]
As was described in #21 I have encountered a similar issue with the V1 library.

The [Log4net.Appender.InfluxDBSyslog](https://github.com/MarkZither/Log4net.Appender.InfluxDBSyslog) logs the ProcId as a string, so where I have multiple applicaitons logging to the same syslog table it fails with 

```
2023-01-26T13:35:56.9871473Z Exception while emitting periodic batch from Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink:
 InfluxData.Net.Common.Infrastructure.InfluxDataApiException: InfluxData API responded with status code=BadRequest, response=
{"error":"partial write: field type conflict: input field \"procid\" on measurement \"syslog\" is type integer, already exists as type string dropped=7"}
```

The impact of this is that tags are written but fields are not, leading to data missing from our dashboards.

As has been done in V2 I would like to make this a string in V1.

PR coming soon.

**Comment by MarkZither** [comment]
if anybody is using this library on V1 apart from me this is going to be a breaking change, and i have a second one for severity_code which I will create a second issue for as i would like to change it to an int.

**Comment by pada57** [comment]
solved by solved by https://www.nuget.org/packages/Serilog.Sinks.InfluxDB.V1.Syslog/2.0.0
