### ISSUE TITLE
Bug: severity_code should be Int not string in V1

### ISSUE THREAD

**Issue by MarkZither** [pada57/serilog-sinks-influxdb#30]
This is mainly to ensure consistency with [Log4net.Appender.InfluxDBSyslog](https://github.com/MarkZither/Log4net.Appender.InfluxDBSyslog) and my interpretation of https://www.rfc-editor.org/rfc/rfc5424#section-6.2.1, the severity_code should be stored as an Int.

**Comment by pada57** [comment]
solved by https://www.nuget.org/packages/Serilog.Sinks.InfluxDB.V1.Syslog/2.0.0
