### ISSUE TITLE
Feature request:Add a option to include / exclude hostname

### ISSUE THREAD

**Issue by linosteenkamp** [pada57/serilog-sinks-influxdb#32]
Current: Hostname is automatically added to the measurement as a tag. We use Serilog.Sinks.InfluxDB.Syslog in our Kubernetes pods and jobs, which gets new hostnames on dynamic events.  This result is an ever-growing list of hostnames which affects cardinality. 

Request: Provide an option to include /exclude the hostname as a tag.

Suggestion: Add a sink option IncludeHostname with a default value of true.
```
"sinkOptions": {
  "IncludeHostname": true,
```

**Comment by tom-englert** [comment]
@linosteenkamp happy to accept your PR to add this feature.

**Comment by linosteenkamp** [comment]
Please see pull request: #33

**Comment by linosteenkamp** [comment]
Included unit tests, please see pull request #34

**Comment by tom-englert** [comment]
You wanted to make more fields optional, do you plan this in the near future?

**Comment by linosteenkamp** [comment]
> 

Yes busy with it now, hopefully, get a PR to you later tonight or tomorrow.

**Comment by linosteenkamp** [comment]
@tom-englert PR #35 is now available to review at your convenience.

**Comment by tom-englert** [comment]
2.3.4 is now live

**Comment by linosteenkamp** [comment]
@tom-englert thank you so much. Much appreciated.
