### ISSUE TITLE
Make all fields optional via configuration

### ISSUE THREAD

**Issue by peitschie** [pada57/serilog-sinks-influxdb#36]
Hi!

I'm using this plugin as part of a Serilog-based data collection solution (mostly because of the batching, filtering and other nice features you've got!).

Basically, I'm wanting to push up the leanest possible payload to InfluxDB, which for my case is a bunch of properties. I have no need for message, facility, procID, etc. etc. I've tested things out locally with a modified version of this, and the data points arrive in-tact with no fields specified, so it seems that InfluxDB has no problems with this.

Would you be open to a pull request that made **all** fields optional, configurable via the same mechanisms as is used for hostname/level/severity/etc.?

Thanks for such a lean and useful Serilog sink 🙂

**Comment by peitschie** [comment]
I've added two possible approaches, just in case either of these is something you're exactly willing to take 🙂

**Comment by tom-englert** [comment]
@peitschie should be available on nuget.org in a few minuts

**Comment by peitschie** [comment]
Thanks so much for that @tom-englert 

I really appreciate the change to collaborate here 🙂
